#lang sicp
(define (call-the-cops)
  (error "Calling 911!"))

(define (make-account balance password)
  (let ((incorrect 0))
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance 
                     (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch p m)
    (if (not (eq? p password))
        (begin (set! incorrect (+ incorrect 1))
               (if (>= incorrect 7)
                   (call-the-cops)
                   (error "Incorrect password")))
        (cond ((eq? m 'withdraw) withdraw)
              ((eq? m 'deposit) deposit)
              (else (error "Unknown request: " m)))))
  dispatch))